### ISSUE TITLE
Translation into Russian

### ISSUE THREAD

**Issue by Gargo** [horitaku46/SilentScrolly#1]
Hello
I've translated the readme into Russian. Add a link to it on my website please:
http://gargo.of.by/silentscrolly/

**Comment by horitaku46** [comment]
Thank you for translating this readme into Russian!
I attached a link!🙇‍♂️
https://github.com/horitaku46/SilentScrolly/commit/86f3ac2006203fee95d796ab963a0d3636cfbf70
